<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>%(title)s</title>
		<meta name="keywords" content="Linux, Firewall, IPCop, IPFire, Security" />
		<meta name="description" content="" />
		<meta name="verify-v1" content="2LEf3W8naILGWVy2dhedSVEHPXTpp2xFNVsHXZMH1JI=" />
		<link rel="stylesheet" type="text/css" href="/include/style.css" />
		<link rel="alternate" type="application/rss+xml" title="RSS" href="http://www.ipfire.org/%(lang)s/news.rss" />
	<!--[if lt IE 7]>
		<link rel="stylesheet" type="text/css" href="/include/ie6.css" />
		<script src="/include/correctpng.js" type="text/javascript"></script>
	<![endif]-->
	</head>
	<body>
		<div id="header">
			<div id="header_inner" class="fixed">
				<div id="logo">
					<a href="/" accesskey="h" title="[ALT+H]"><img src="/images/tux2-99.png" width="100px" height="102px" class="symbol" alt="IPFire" /></a>
				</div>
				<div id="line1">
					%(menu)s
					<div id="lang">
						%(languages)s
					</div>
				</div>
				<div id="line2">
					<h1>%(server)s</h1>
				</div>
				<div id="line3">
					<h2>%(slogan)s</h2>
				</div>
				
			</div>
		</div>
		<div id="main">
		    <div id="main_inner" class="fixed">
				<table>
	    			<tr>
						<td id="sh-tl"></td>
						<td id="sh-top"></td>
						<td id="sh-tr"></td>
					</tr>
					<tr>
						<td id="sh-lft"></td>
						<td id="no-sh">
							<div id="primaryContent_2columns">
								<div id="columnA_2columns">
									%(content)s
									<br class="clear" />
								</div>
							</div>
							<div id="secondaryContent_2columns">
								<div id="columnC_2columns">
									%(sidebar)s
									<br class="clear" />
								</div>
							</div>
						</td>
						<td id="sh-rgt"></td>
					</tr>
					
					<tr>
						<td id="sh-lft"></td>
						<td id="footer" class="fixed2">
							Copyright &copy; %(year)s IPFire.org. All rights reserved. <a href="/%(lang)s/imprint">Imprint</a>
						</td>
						<td id="sh-rgt"></td>
					</tr>
					
					<tr>
						<td id="sh-bl"></td>
						<td id="sh-btn"></td>
						<td id="sh-br"></td>
					</tr>
				</table>
			</div>
		</div>
	</body>
</html>
